const nba_teams = {
  "Atlanta Hawks": "ATL",
  "atl-hawks": "ATL",
  "Boston Celtics": "BOS",
  "bos-celtics": "BOS",
  "Brooklyn Nets": "BKN",
  "bkn-nets": "BKN",
  "Charlotte Hornets": "CHA",
  "cha-hornets": "CHA",
  "Charlotte Bobcats": "CHA",
  "Chicago Bulls": "CHI",
  "chi-bulls": "CHI",
  "Cleveland Cavaliers": "CLE",
  "cle-cavaliers": "CLE",
  "Dallas Mavericks": "DAL",
  "dal-mavericks": "DAL",
  "Denver Nuggets": "DEN",
  "den-nuggets": "DEN",
  "Detroit Pistons": "DET",
  "det-pistons": "DET",
  "Golden State Warriors": "GS",
  "gs-warriors": "GS",
  "Houston Rockets": "HOU",
  "hou-rockets": "HOU",
  "Indiana Pacers": "IND",
  "ind-pacers": "IND",
  "LA Clippers": "LAC",
  "la-clippers": "LAC",
  "Los Angeles Lakers": "LAL",
  "la-lakers": "LAL",
  "Memphis Grizzlies": "MEM",
  "mem-grizzlies": "MEM",
  "Miami Heat": "MIA",
  "mia-heat": "MIA",
  "Milwaukee Bucks": "MIL",
  "mil-bucks": "MIL",
  "Minnesota Timberwolves": "MIN",
  "min-timberwolves": "MIN",
  "New Orleans Hornets": "NO",
  "New Orleans Pelicans": "NO",
  "no-pelicans": "NO",
  "New York Knicks": "NYK",
  "ny-knicks": "NY",
  "Oklahoma City Thunder": "OKC",
  "okc-thunder": "OKC",
  "Orlando Magic": "ORL",
  "orl-magic": "ORL",
  "Philadelphia 76ers": "PHI",
  "phi-76ers": "PHI",
  "Phoenix Suns": "PHX",
  "pho-suns": "PHX",
  "Portland Trail Blazers": "POR",
  "por-trail-blazers": "POR",
  "Sacramento Kings": "SAC",
  "sac-kings": "SAC",
  "San Antonio Spurs": "SAS",
  "sa-spurs": "SAS",
  "Toronto Raptors": "TOR",
  "tor-raptors": "TOR",
  "Utah Jazz": "UTAH",
  "uta-jazz": "UTAH",
  "Washington Wizards": "WAS",
  "was-wizards": "WAS",
  "Seattle SuperSonics": "OKC",
  "Vancouver Grizzlies": "MEM",
  "New Jersey Nets": "BKN",
};

module.exports = { nba_teams };
